networks:
    my-rinha:
        driver: bridge

services:
    database:
        image: postgres:16.4
        hostname: db
        container_name: my-postgres-rinha
        networks:
            - my-rinha
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pessoas_data
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: '1.35GB'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

    api1: &api
        build: .
        image: my-rinha-app:1.0
        container_name: api1-my-rinha-app
        networks:
            - my-rinha
        expose:
            - "8080"
        environment:
            DB_HOST: db
        depends_on:
            - database
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.6GB'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/contagem-pessoas"]
            interval: 5s
            timeout: 5s
            retries: 20

    api2:
        <<: *api
        container_name: api2-my-rinha-app

    nginx:
        image: nginx:stable-alpine
        container_name: nginx-rinha
        networks:
            - my-rinha
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
        ports:
            - 9999:9999
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.45GB'
